# Generated by tools/environment_art_pipeline.py. Do not edit by hand.
class_name FacilityEnvironmentCatalog
extends RefCounted

const ROOM_FAMILIES: Dictionary[StringName, StringName] = {
	&"external_infiltration_yard": &"yard",
	&"reception_checkpoint": &"corporate",
	&"staff_office": &"corporate",
	&"locker_room": &"corporate",
	&"security_office": &"corporate",
	&"guard_break_room": &"corporate",
	&"cctv_control_room": &"systems",
	&"electrical_room": &"systems",
	&"server_room": &"systems",
	&"research_laboratory": &"research",
	&"laser_corridor": &"research",
	&"vault_antechamber": &"vault",
	&"chronos_vault": &"vault",
	&"maintenance_passage": &"service",
	&"extraction_route": &"service",
}

const ROOM_SEEDS: Dictionary[StringName, int] = {
	&"external_infiltration_yard": 17,
	&"reception_checkpoint": 29,
	&"staff_office": 37,
	&"locker_room": 43,
	&"security_office": 53,
	&"guard_break_room": 61,
	&"cctv_control_room": 71,
	&"electrical_room": 79,
	&"server_room": 89,
	&"research_laboratory": 97,
	&"laser_corridor": 107,
	&"vault_antechamber": 113,
	&"chronos_vault": 127,
	&"maintenance_passage": 137,
	&"extraction_route": 149,
}

const FLOOR_TILES: Dictionary[StringName, Array] = {
	&"yard": [Vector2i(0, 0), Vector2i(1, 0)],
	&"corporate": [Vector2i(2, 0), Vector2i(3, 0)],
	&"systems": [Vector2i(4, 0), Vector2i(5, 0)],
	&"research": [Vector2i(6, 0), Vector2i(7, 0)],
	&"vault": [Vector2i(8, 0), Vector2i(9, 0)],
	&"service": [Vector2i(10, 0), Vector2i(11, 0)],
	&"neutral": [Vector2i(12, 0), Vector2i(13, 0)],
}

const DETAIL_TILES: Dictionary[StringName, Array] = {
	&"yard": [Vector2i(0, 1), Vector2i(1, 1)],
	&"corporate": [Vector2i(2, 1), Vector2i(3, 1)],
	&"systems": [Vector2i(4, 1), Vector2i(5, 1)],
	&"research": [Vector2i(6, 1), Vector2i(7, 1)],
	&"vault": [Vector2i(8, 1), Vector2i(9, 1)],
	&"service": [Vector2i(10, 1), Vector2i(11, 1)],
}

const SEMANTIC_SOLIDS: Dictionary[StringName, StringName] = {
	&"reception_desk": &"reception_desk",
	&"locker_bank_north": &"locker_bank",
	&"locker_bank_south": &"locker_bank",
	&"staff_desk_west": &"office_desk",
	&"staff_desk_east": &"office_desk",
	&"guard_break_table": &"break_table",
	&"cctv_monitor_bank": &"cctv_monitor_bank",
	&"security_desk": &"security_desk",
	&"electrical_cabinet_west": &"electrical_cabinet",
	&"electrical_cabinet_east": &"electrical_cabinet",
	&"server_rack_west": &"server_rack",
	&"server_rack_east": &"server_rack",
	&"research_bench_north": &"research_bench",
	&"research_bench_south": &"research_bench",
	&"maintenance_machine_west": &"maintenance_machine",
	&"maintenance_machine_east": &"maintenance_machine",
}

const MOTIF_TILES: Dictionary[StringName, Array] = {
	&"reception_desk": [Vector2i(0, 4), Vector2i(1, 4), Vector2i(2, 4)],
	&"locker_bank": [Vector2i(3, 4), Vector2i(4, 4), Vector2i(5, 4)],
	&"office_desk": [Vector2i(6, 4), Vector2i(7, 4)],
	&"break_table": [Vector2i(8, 4), Vector2i(9, 4)],
	&"cctv_monitor_bank": [Vector2i(10, 4), Vector2i(11, 4), Vector2i(12, 4), Vector2i(13, 4)],
	&"security_desk": [Vector2i(14, 4), Vector2i(15, 4), Vector2i(0, 5), Vector2i(1, 5)],
	&"electrical_cabinet": [Vector2i(2, 5), Vector2i(3, 5), Vector2i(4, 5)],
	&"server_rack": [Vector2i(5, 5), Vector2i(6, 5), Vector2i(7, 5)],
	&"research_bench": [Vector2i(8, 5), Vector2i(9, 5), Vector2i(10, 5)],
	&"maintenance_machine": [Vector2i(11, 5), Vector2i(12, 5), Vector2i(13, 5), Vector2i(14, 5), Vector2i(15, 5), Vector2i(0, 6)],
}

const VAULT_RING_TILES: Dictionary[Vector2i, Vector2i] = {
	Vector2i(0, 0): Vector2i(0, 8),
	Vector2i(1, 0): Vector2i(1, 8),
	Vector2i(2, 0): Vector2i(2, 8),
	Vector2i(0, 1): Vector2i(3, 8),
	Vector2i(1, 1): Vector2i(4, 8),
	Vector2i(2, 1): Vector2i(5, 8),
	Vector2i(0, 2): Vector2i(6, 8),
	Vector2i(1, 2): Vector2i(7, 8),
	Vector2i(2, 2): Vector2i(8, 8),
}
